@startmindmap
title Self Educated Programmer: Junior level /git.puml

* Git
** Release mechanism
*** flow
** Tags
** Conflicts
** Rebasing
** Branching
*** forking point
*** feature branch
*** release branch
*** good branch name
** Merging
** Commits
*** structure
*** good title
*** good content
*** Commit editing 
*** Commit cherrypick
** submodules
*** init / update / add / remove
*** hierarchical linkage use
@endmindmap
