@startmindmap
title Self Educated Programmer: Junior level

* Student
** Basic Computer (see ./basic_computer.puml)
** Basic Networking (see ./network.puml)
** Linux (see ./linux.puml)
** Git (see ./git.puml)
** Editors (see ./editors.puml)
** Development workflow (see ./dev_flow.puml)
** Documentation (see ./docs.puml)
** Testing workflow (see ./testing.puml)
** DevOps workflow (see ./devops.puml)

@endmindmap
