@startmindmap
title Self Educated Programmer: Student level

* start
** Communication
*** English
*** Remote Colaboration
**** Common Tools
**** Tips/Tricks
*** Behavior
** PC usage
*** Windows
*** Linux
*** Administration
*** Typing
*** Office Tools
**** Word / PowerPoint / Excel




@endmindmap
