@startmindmap
title Self Educated Programmer: Junior level /basic_computer.puml

* Basic Computer
** Processes
** Threads
** Sockets
** HW
*** RAM Memory
*** CPU
*** Storage
**** SSD
**** HDD
**** USB-mass-Storage 

@endmindmap
