@startmindmap
title Self Educated Programmer: Junior level /docs.puml

* Documentation
** WYSIWYG
*** *.md
*** PlantUML
*** *.adoc
** C/C++
*** doxygen
** Python
*** sphinx / readthedocs 

@endmindmap
