@startmindmap
title Self Educated Programmer: Junior level /linux.puml


* Linux
** Netwokring
*** interfaces
**** Ethernet
**** Wifi
**** virtual
***** bridge
*** get status
**** list of intefaces and addresses `ip a`
** sudo
** configuration
*** system wide configuration (/etc/)
*** environment variables
** Terminal (Shells)
*** commands
**** navigation
***** ls / ll / find / tree
***** cd
***** pushd / popd
**** pipe
**** file permissions
***** chmod
***** chown
**** List TCP connections
***** netstat
***** ss
**** Processes list
***** ps -fax
***** kill
****** signals
*** bash
**** aliases
**** language basics
***** if
***** for / while
***** functions
***** variables
*** sh
**** difference with other interpreters
**** busybox
** user management
*** user groups
** File permissions
*** user
*** group
*** other
** kernel partitions
*** /proc/
*** /sys/
*** tmpfs
*** mounts
**** overlays
**** softlinks / hardlinks
** systemd
*** journalctl
*** systemctl
** Kernel Space
** User Space
*** stdout, stderr, stdin
*** Posix API
**** File Descriptors
**** Socket API
** typical RootFS structure
** security
** Remote access
*** SSH
*** Remote Desktop
**** VNC
**** Teamviewer


@endmindmap
