@startmindmap
title Self Educated Programmer: Student level

* start
** Communication
*** English
**** Reading
**** Communication 
**** Written
*** Remote Colaboration
**** Video Conferences
***** Teams
***** Zoom
**** Chats
***** Teams
***** Slack
***** Mattermost
**** Tips/Tricks
*** Behavior
**** Constructive
**** Motivated 
**** On-Time (Puntually)
**** Polite
***** Respectfull

** PC user level usage
*** Windows
*** Linux
*** Typing
*** Office Tools
**** Word / PowerPoint / Excel
*** Text Editors

** Searching Skills
*** Official Documentation
*** Google it
*** ChatGPT
*** CoPilot
*** StackOverflow
*** Forums

@endmindmap
