@startmindmap
title Self Educated Programmer: Junior level /testing.puml

* Testing
** types

*** by components
**** unit
**** integration
**** system
**** e2e
**** hardware
**** software

*** how big
**** smoke
**** exploratory
**** adhoc
**** differencial / partial
**** incremental
**** continuous
**** re-test
**** regression

*** by scope 
**** compatibility 
**** acceptance
***** factory
***** site
**** gated
**** (un-) official
**** monkey / random
**** fuzz testing
**** Qualification / Certification
**** Dynamic / Static

*** by TC design technique
**** Model-Based testing
**** Risk-based testing
**** blackbox / whitebox
**** requirements based testing
**** experience-based testing
**** Test-Driven Development
***** Design driven testing

*** by means
**** manual / automatic 
**** semi-automatic
**** interactive / headless

*** by functionality
**** performance
**** security 
**** functional / non-functional
**** resilience 
**** load
**** stress
**** scalability
**** sanity
**** usability
**** fesability
**** documentation
**** accesibility
**** requirements

*** by type of audience
**** beta / alfa
**** A/B 
**** user
**** developer

** Definitions
*** Test-Case
*** Test-step
*** Expected-result
*** Test-Suite
*** Test-Run
*** Test-strategy
**** Quality plan 
**** Guide 
*** Test-Plan / Loop
*** Test-Management
*** Test-Report
*** Anomaly-Report
*** Test-Traceability (Matrix)

** Testing Tools
*** ADO
@endmindmap
