@startmindmap
title Self Educated Programmer: Junior level ./virtualization.puml

* Virtualization
** Docker
*** Image
**** Building
**** layers
*** Container
**** mounts
**** networking
*** Registry
*** Compose
*** Commands
**** login
**** build
**** pull
**** run 
**** exec
** Kubernetes
*** installation
*** resources
**** pods
**** networking
*** kubectl CLI
**** get {api-resources}
@endmindmap
